# Generated by Django 5.0.7 on 2024-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo1', models.CharField(choices=[('Normal', 'Normal'), ('Psíquico', 'Psíquico'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Electrico', 'Electrico'), ('Planta', 'Planta'), ('Lucha', 'Lucha'), ('Hielo', 'Hielo'), ('Volador', 'Volador'), ('Bicho', 'Bicho'), ('Veneno', 'Veneno'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Dragon', 'Dragon'), ('Tierra', 'Tierra'), ('Hada', 'Hada')], default='Normal', max_length=50)),
                ('tipo2', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Psíquico', 'Psíquico'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Electrico', 'Electrico'), ('Planta', 'Planta'), ('Lucha', 'Lucha'), ('Hielo', 'Hielo'), ('Volador', 'Volador'), ('Bicho', 'Bicho'), ('Veneno', 'Veneno'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Dragon', 'Dragon'), ('Tierra', 'Tierra'), ('Hada', 'Hada')], max_length=50, null=True)),
                ('region', models.CharField(choices=[('Kanto', 'Kanto'), ('Johto', 'Johto'), ('Hoenn', 'Hoenn'), ('Sinnoh', 'Sinnoh'), ('Teselia', 'Teselia'), ('Kalos', 'Kalos'), ('Alola', 'Alola'), ('Galar', 'Galar'), ('Paldea', 'Paldea'), ('Almia', 'Almia'), ('Aura', 'Aura')], default='Kanto', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
